(ns antizer.antd)

(def components '[Affix
                  Alert
                  AutoComplete
                  AutoComplete.OptGroup
                  AutoComplete.Option
                  Avatar
                  BackTop
                  Badge
                  Breadcrumb
                  Breadcrumb.Item
                  Button
                  Button.Group
                  Card
                  Card.Grid
                  Card.Meta
                  Checkbox
                  Checkbox.Group
                  Col
                  DatePicker
                  DatePicker.MonthPicker
                  DatePicker.RangePicker
                  DatePicker.WeekPicker
                  Divider
                  Form
                  Form.Item
                  Icon
                  Input
                  Input.Group
                  Input.Search
                  Input.TextArea
                  InputNumber
                  Layout
                  Layout.Content
                  Layout.Footer
                  Layout.Header
                  Layout.Sider
                  LocaleProvider
                  Mention
                  Mention.Nav
                  Menu
                  Menu.Divider
                  Menu.Item
                  Menu.ItemGroup
                  Menu.SubMenu
                  Modal
                  Progress
                  Radio
                  Radio.Button
                  Radio.Group
                  Row
                  Select
                  Select.OptGroup
                  Select.Option
                  Spin
                  Steps
                  Steps.Step
                  Switch
                  Tabs
                  Tabs.TabPane
                  Tag
                  Tag.CheckableTag
                  TimePicker
                  Timeline
                  Timeline.Item
                  Tooltip
                  Upload])

(def props '[locales])

(def funcs '[message.config
             message.destroy
             message.error
             message.info
             message.loading
             message.success
             message.warn
             message.warning
             Modal.confirm
             Modal.error
             Modal.info
             Modal.success
             Modal.warning
             notification.close
             notification.config
             notification.destroy
             notification.error
             notification.info
             notification.open
             notification.success
             notification.warn
             notification.warning])

(def form-funcs '[getFieldDecorator
                  getFieldError
                  getFieldsError
                  getFieldsValue
                  getFieldValue
                  isFieldsTouched
                  isFieldTouched
                  isFieldValidating
                  resetFields
                  setFields
                  setFieldsValue
                  validateFields
                  validateFieldsAndScroll])
